Use types from std::os::raw instead of libc where possible
overdrivenpotato/rust-vst2 pull request #31
Opened 2017-06-05 05:55 UTC by Boscop

Now plugins don't need to depend on libc for `Plugin::open()`.

I also made `load_pointer` uppercase (`LOAD_POINTER`) because it's a global var and caused a warning.

2017-06-05 13:33 UTC, overdrivenpotato commented
Tests appear to be failing, I'll merge it in if you can fix the build

2017-06-05 18:35 UTC, overdrivenpotato requested changes
Missed this earlier, looks good otherwise

2017-06-05 18:35 UTC, overdrivenpotato commented on src/interfaces.rs
> +            strncpy(ptr as *mut c_char,
Let's leave this line as `libc::strncpy` to make it clear that we are not implementing our own.

2017-06-06 02:47 UTC, Boscop commented
Both local closures of `copy_string` were the same (from copy pasting last year) so I moved it out into a function and removed the allocations: `string.clone()` and `CString::new()` were both allocating and walking the string.

2017-06-07 08:06 UTC, robsaunders commented
Can we merge this asap as I'm waiting on this fix.

Perhaps boscop should have the ability to merge PRs?

2017-06-09 19:51 UTC, zyvitski commented
I second the motion to merge.

2017-06-13 13:15 UTC, merged

2017-06-13 13:15 UTC, overdrivenpotato commented
I'll try and be quicker regarding future PRs, the last few days were fairly busy for me.